### PR TITLE
add monkey 🐒

### PR DESCRIPTION
**Pull request by LucyMcGowan**
I added a monkey -- I feel like this was a very small contribution, but I am happy to update the contributors list if you prefer.

### CODE REVIEW

**Comment by sckott** [comment]
awesome!  plz do update the contributors list with your name!

**Comment by LucyMcGowan** [comment]
I changed the readme & description, but it seems to have failed 👆🏼, let me know if there is something I should change. thanks!

**Comment by sckott** [comment]
there's a minor thing in the `DESCRIPTION` file. R doesn't like this newline here https://github.com/LucyMcGowan/cowsay/blob/master/DESCRIPTION#L18 - remove that and push again

**Comment by LucyMcGowan** [comment]
awesome, updated. thank you!

**Comment by sckott** [comment]
awesome, nice work @LucyMcGowan 

thanks so so much for your contribution!

**Pull request merged**
