### PR TITLE
Remove extraneous commas from animals.r

### PR DESCRIPTION
**Pull request by kbroman**
- When the animals were converted to a vector, commas were added to
   every line containing an =, even if it was within a character
   (this was part of PR #24), specifically [this commit](https://github.com/ateucher/cowsay/commit/7010a544b1).

### CODE REVIEW

**Comment by ateucher** [comment]
Whoops, that was me (multiple cursors gone wild). Thanks!

**Comment by sckott** [comment]
nice catch @kbroman - no worries @ateucher - this isn't nasa mission critical code, so we're cool (p.s. it is fun critical code)

**Comment by kbroman** [comment]
I think maybe there's a dissertation here, on testing ascii cat functions.

**Comment by sckott** [comment]
:+1:

**Pull request merged**
