### PR TITLE
If colors are non-null, check that coloring is possible

### PR DESCRIPTION
**Pull request by aedobbyn**
I didn't put the `crayon::has_color()` check in `cowsay:::check_color()` because it checks both `what_color` and `by_color`, so would message twice if color can't be applied. Def open to other ways of doing this, though.

### CODE REVIEW

**Comment by sckott** [comment]
thanks for this @aedobbyn ! - on vacation now, will respond mid next week

**Comment by aedobbyn** [comment]
No rush! Enjoy!

**Comment by sckott** [comment]
back from vacay. 

@aedobbyn  Looks like there's some test fails https://travis-ci.org/sckott/cowsay/builds/421368527#L1238-L1252 any thoughts?

**Comment by aedobbyn** [comment]
oh my bad, I didn't check the CI stuff. I think this is because colors on the server can't be applied so it bypasses the check and [sets `what_color` and `by_color` to null](https://github.com/sckott/cowsay/pull/61/files#diff-800808ac8c9da970e0b4a8fba9179707R137) instead of jumping into `check_color`, where the error would be triggered.

so I think we can skip those two tests if `crayon::has_color` is false (I'll push that change) or take some similar approach

**Comment by sckott** [comment]
looks good, thanks!

**Pull request merged**
