### PR TITLE
Add some color examples to readme

### PR DESCRIPTION
**Pull request by aedobbyn**
These are just screenshots but they eliminate the warning when color is added to animals in the readme and show what the colors can look like. Heights of the images might still be a bit off (I don't at all have an eye for this) so of course am happy to change them.

### CODE REVIEW

**Comment by sckott** [comment]
cool, let me know when you're done with commits to this pr

**Comment by aedobbyn** [comment]
Okay haha sorry I think it should be good to go now

**Comment by sckott** [comment]
sorry for the delay , looking at now

**Comment by sckott** [comment]
looks good to me

**Comment by aedobbyn** [comment]
wooo!

**Pull request merged**
