### PR TITLE
Adding two ascii art squirrels.

### PR DESCRIPTION
**Pull request by marionlouveaux**
## Description
Hi,
I added two ascii art squirrels. I drew these squirrels myself using this Flickr image as a background template: https://www.flickr.com/photos/hedera_baltica/44806157514/in/photostream/
I made sure package passes checks and tests.

## Related Issue
No related issue

### CODE REVIEW

**Comment by sckott** [comment]
thanks @marionlouveaux ! Having a look

**Comment by marionlouveaux** [comment]
Hi,
Thanks for looking at it!
I changed my initials to ML.
Yes, the only difference between the two is the eye.

**Comment by sckott** [comment]
thanks @marionlouveaux looks good!

**Comment by sckott** [comment]
thanks for your contribution. i'll add your name to the pkg after merging

**Comment by marionlouveaux** [comment]
Thanks a lot!

**Pull request merged**
