### PR TITLE
while loop doesn't automatically fail w/ n == Inf

### PR DESCRIPTION
**Pull request by davharris**

### CODE REVIEW

**Comment by sckott** [comment]
thanks @davharris - good catch

**Comment by sckott** [comment]
@davharris know any way to make the loop break if `esc`/ctrl-c used?

**Comment by davharris** [comment]
Haha.  I don’t really know anything about what’s going on under the hood when R asks for user input, and I didn’t see an answer in `?readline` or in a quick google search.

Might need to set different break condition or use a different input method?

**Comment by sckott** [comment]
hmm, actually ctrl-c is fine in R.app or on the CLI, but not working in Rstudio.

**Pull request merged**
