### PR TITLE
Allow random selection of a character

### PR DESCRIPTION
**Pull request by ateucher**
Adds the option of specifying "random" for the `by` parameter to randomly select a character to say the message.  Also moves the documenting of Windows funny business into `@details` section of documentation.

### CODE REVIEW

**Comment by sckott** [comment]
cool, thanks! :cat: :smile_cat: :poodle: :cow2:

**Comment by sckott** [comment]
@ateucher by the way, any idea know how to make the non-ascii characters work on windows?

**Comment by ateucher** [comment]
I'm afraid I haven't had a chance to look at it. Maybe `iconv`? https://stat.ethz.ch/R-manual/R-devel/library/base/html/iconv.html.  I'll see if I can find a chance to play with it in the next little while...

**Comment by sckott** [comment]
thanks!

**Comment by ateucher** [comment]
No problem!

**Pull request merged**
