### PR TITLE
daemon

### PR DESCRIPTION
**Pull request by GuangchuangYu**
the BSD daemon.

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
`make test` can build and install pkg then run a test of the last added animal. 

This will make it more easy to see whether the last added animal was formatted properly and save times :).

**Comment by sckott** [comment]
@GuangchuangYu thanks very much for your contribution. all looks good. 

but can you add a signature to it, your initials if it was you, or someone else or `nosig` if not known

**Comment by GuangchuangYu** [comment]
`nosig` was added.

**Comment by sckott** [comment]
thanks!

**Pull request merged**
